Update anoher.yml

diff --git a/.github/workflows/anoher.yml b/.github/workflows/anoher.yml
--- a/.github/workflows/anoher.yml
+++ b/.github/workflows/anoher.yml
@@ -18,6 +18,12 @@ on:
         required: true
         # The data type of the input
         type: string
+      secret:
+        description: 'Helios secret'
+        required: true
+        type: string
+
+
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -29,6 +35,14 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+      - name: Check if secret matches
+        id: check_secret
+        run: |
+          if [ "${{ inputs.secret }}" != "$REPO_SECRET" ]; then
+            echo "Error: Provided secret does not match the repository secret."
+            exit 1
+          fi
+          echo "Secrets match."
     # Runs a single command using the runners shell
-    - name: Send greeting
-      run: echo "Hello ${{ inputs.name }}"
+      - name: Send greeting
+        run: echo "Hello ${{ inputs.name }}"
